const STORAGE_KEY='xFollowReviewProbe.events';let currentEvents=[];const $=id=>document.getElementById(id);
function latestByOperation(events){const map=new Map();for(const event of events){if(!event.operation)continue;const g=map.get(event.operation)||{operation:event.operation,events:[]};g.events.push(event);map.set(event.operation,g)}return[...map.values()].map(g=>{const sorted=g.events.sort((a,b)=>(b.capturedAt||0)-(a.capturedAt||0));const shapeEvent=sorted.find(e=>e.kind==='response-shape'&&e.response?.shape);const responseMeta=sorted.find(e=>e.status!=null);return{operation:g.operation,queryId:sorted.find(e=>e.queryId)?.queryId||'',method:sorted.find(e=>e.method)?.method||'',status:responseMeta?.status??'',hasShape:Boolean(shapeEvent),lastAt:sorted[0]?.capturedAt||0,representative:shapeEvent||sorted[0],events:sorted}}).sort((a,b)=>b.lastAt-a.lastAt)}
function fmtTime(ms){return ms?new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(ms)):''}
function setStatus(id,names){const el=$(id);el.textContent=names.length?`観測済み: ${names.slice(0,3).join(', ')}`:'未観測';el.classList.toggle('ok',names.length>0)}
function render(events){currentEvents=events;const groups=latestByOperation(events);$('count').textContent=`${groups.length} operations / ${events.length} events`;const rows=$('rows');rows.textContent='';for(const g of groups){const tr=document.createElement('tr');for(const v of [g.operation,g.queryId,g.method,String(g.status),g.hasShape?'yes':'no',fmtTime(g.lastAt)]){const td=document.createElement('td');td.textContent=v;tr.appendChild(td)}tr.addEventListener('click',()=>{$('detail-help').style.display='none';$('detail').textContent=JSON.stringify({operation:g.operation,latestUsefulEvent:g.representative,recentEvents:g.events.slice(0,5)},null,2)});rows.appendChild(tr)}const names=groups.map(g=>g.operation);setStatus('status-following',names.filter(n=>n.toLowerCase().includes('following')));setStatus('status-bookmarks',names.filter(n=>n.toLowerCase().includes('bookmark')));setStatus('status-media',names.filter(n=>/usermedia|media/i.test(n)));setStatus('status-lists',names.filter(n=>/listmanagement|listmembers|listownership|listmembership/i.test(n)))}
async function load(){const stored=await chrome.storage.local.get(STORAGE_KEY);render(Array.isArray(stored[STORAGE_KEY])?stored[STORAGE_KEY]:[])}
$('refresh').addEventListener('click',load);$('clear').addEventListener('click',async()=>{await chrome.storage.local.remove(STORAGE_KEY);$('detail').textContent='';$('detail-help').style.display='';render([])});
$('copy').addEventListener('click',async()=>{const useful=latestByOperation(currentEvents).map(g=>({operation:g.operation,queryId:g.queryId,method:g.method,status:g.status,responseShapeCaptured:g.hasShape,event:(()=>{const {tabUrl,requestId,capturedAt,...safe}=g.representative||{};return safe})()}));await navigator.clipboard.writeText(JSON.stringify({generatedAt:new Date().toISOString(),note:'No Authorization/Cookie/CSRF values are intentionally stored by this probe.',operations:useful},null,2));const btn=$('copy');const old=btn.textContent;btn.textContent='コピーしました';setTimeout(()=>btn.textContent=old,1200)});
chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes[STORAGE_KEY])render(Array.isArray(changes[STORAGE_KEY].newValue)?changes[STORAGE_KEY].newValue:[])});load();
